### ISSUE TITLE
添加Artitalk后leancloud国内版报错

### ISSUE THREAD

**Issue by adil-zhang** [jerryc127/butterfly-plugins#1]
已添加配置项
    option:
      serverURL: 自己绑定的域名
      lang: zh

可是有一些奇怪的报错，详细地址如下
https://blog.adil.com.cn/artitalk/

**Comment by adil-zhang** [comment]
html.pug好像有一些奇怪的问题，导致没办法正确读取option内容
https://github.com/jerryc127/butterfly-plugins/blob/ee1333d940d26acf9fdfb365462c1dda1f75319c/hexo-butterfly-artitalk/lib/html.pug#L10

**Comment by jerryc127** [comment]
你的網站正常啊
所以你反饋的啥

**Comment by jerryc127** [comment]
如果沒有正確讀取 那你的artitalk就無法加載了

**Comment by adil-zhang** [comment]
我调整了我上面写的那一行，为
```
const otherSetting = {"serverURL":"我的域名","lang":"zh"}
```
然后正常了

**Comment by adil-zhang** [comment]
我调整为没改之前的内容了，你这边帮忙看下。

**Comment by jerryc127** [comment]
已修復
