### ISSUE TITLE
关于npm安装hexo-butterfly-extjs后运行hexo g提示找不到Waline.js的问题

### ISSUE THREAD

**Issue by 991688344** [jerryc127/butterfly-plugins#28]
- 系统manjao
- npm版本: 8.10.0
- node版本: v18.1.0
- @waline/client版本: 2.4.2

# BUG复现
- 将主题配置文件中的`third_party_provider: jsdelivr`更改为`third_party_provider: local`
- 博客根目录执行`npm install hexo-butterfly-extjs --save`
- 博客根目录执行`hexo clean && hexo g && hexo s`，这步操作会出现`Warn`提示并中断执行。
具体报错如下:
```
WARN  Please reinstall hexo-butterfly-extjs, run npm install hexo-butterfly-extjs.
WARN  The file does not exist: @waline/client/dist/Waline.js
WARN  The file does not exist: @waline/client/dist/Waline.css
```
# BUG原因
经检查发现是`hexo-butterfly-extjs/plugins.yml`中第11-12行末尾把`waline.js`,`wanline.css`首字母进行了大写，应改为小写

https://github.com/jerryc127/butterfly-plugins/blob/56bc3cb879e172bcd5ea4824e51401b9ad860b55/hexo-butterfly-extjs/plugins.yml#L11
https://github.com/jerryc127/butterfly-plugins/blob/56bc3cb879e172bcd5ea4824e51401b9ad860b55/hexo-butterfly-extjs/plugins.yml#L12

# 本地临时解决的方法
将本地文件`waline.js`,`waline.css`文件名也改为大写
```
$ cp node_modules/@waline/client/dist/waline.js node_modules/@waline/client/dist/Waline.js
$ cp node_modules/@waline/client/dist/waline.css node_modules/@waline/client/dist/Waline.css
```

**Comment by jerryc127** [comment]
windows 下能正常加载 难道 linux 不行。。

下个版本我改下

**Comment by jerryc127** [comment]
已发布
