### ISSUE TITLE
serverURL option is required for apps from CN region

### ISSUE THREAD

**Issue by wang-xiaowu** [jerryc127/butterfly-plugins#37]
作者您好, leancloud我使用的是国际版, 请问为什么还强制中国地区呢

![image](https://user-images.githubusercontent.com/44340137/176348383-b1eb72ca-c8db-4a46-a85e-292230c16f01.png)

**Comment by jerryc127** [comment]
不清楚 确认你填的是国际版的链接
有问题去插件方反馈

**Comment by wang-xiaowu** [comment]
> 不清楚 确认你填的是国际版的链接 有问题去插件方反馈

好的
