### ISSUE TITLE
在电影页面有个小bug

### ISSUE THREAD

**Issue by melonyxin** [jerryc127/butterfly-plugins#4]
在butterfly-plugins/hexo-butterfly-douban/lib/templates/movieWatched.ejs 此文件中的第六行
在img标签后多了一个/div，这会导致页面布局出错。

**Comment by jerryc127** [comment]
https://github.com/jerryc127/butterfly-plugins/commit/0172ce9e85e33d1ee1cd77149458bb46a42fcf64
