### ISSUE TITLE
artitalk功能不稳定

### ISSUE THREAD

**Issue by Iambihua** [jerryc127/butterfly-plugins#5]
部署至gayhub后，功能有点不稳定，
有时一直在下载中，很少显示内容，看了其他博客的示例，都是秒加载。

**Comment by W4J1e** [comment]
也许你遇到的问题是打开一直显示加载中，但是始终无法加载出内容，手动刷新一次就好了。
如果是这个现象，那么就是pjax造成的，在pjax配置中ban掉这个路径。
