### ISSUE TITLE
hexo-douban昨天已经新增了音乐模块

### ISSUE THREAD

**Issue by itgoyo** [jerryc127/butterfly-plugins#63]
RT，不知道这款插件是否也能实现？
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/23348551/208058294-cd5d14a6-958e-4dce-ad29-dcb2779040fd.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/23348551/208058336-e23150d8-c1ce-41ca-808a-ea0dde445d16.png">

**Comment by jerryc127** [comment]
好
我有空的时候同步下代码

**Comment by jerryc127** [comment]
hexo-douban 已经合并了我的请求

后续 hexo-douban-butterfly 应该不会更新了 直接用 hexo-douban 就行
