### ISSUE TITLE
请问下，这个豆瓣的插件我看他电影只能抓500部是么？

### ISSUE THREAD

**Issue by Jinhui1988** [jerryc127/butterfly-plugins#7]
请问下，这个豆瓣的插件我看他电影只能抓500部是么？不能再多了么？

**Comment by jerryc127** [comment]
你是不是设置了 limit

**Comment by Jinhui1988** [comment]
limit都是默认，没改，好像还有个情况就是，好像第一次把这个code写到config后，第一次运行，会加载出来500部电影，还有一些书等，但是第二次部署博客的时候或者本地预览的时候，就都成加载0部了，没了，不知道咋回事

**Comment by jerryc127** [comment]
代码并没有限制爬多少电影
limit 是限制爬的页数。
或许你可以查看 
https://movie.douban.com/people/你的id/collect
看看是不是豆瓣只显示500部

0 部 估计是你爬的太多
被豆瓣限制了
等 第二天 或者换个 ip
