### ISSUE TITLE
主题版本4.5.1，安装hexo-butterfly-extjs报错

### ISSUE THREAD

**Issue by nanbowan323** [jerryc127/butterfly-plugins#84]
使用npm install hexo-butterfly-extjs安装后，本地启动提示：
WARN  Please update theme to V4.8.0 or higher
WARN  Or install hexo-butterfly-extjs to old version
WARN  npm install hexo-butterfly-extjs@1.3.4

使用npm install hexo-butterfly-extjs@1.3.4，本地启动提示：
WARN Please reinstall hexo-butterfly-extjsThe file does not exist:
WARN typed.js/lib/typed.min.js

请问如何在不升级主题版本的情况下正常使用hexo-butterfly-extjs，使CDN为local。

**Comment by jerryc127** [comment]
你把 node_modules 删了

重新 npm install 安装

**Comment by ericjuice** [comment]
去官网：https://fastly.jsdelivr.net/npm/typed.js/lib/typed.min.js，下载这个文件。然后扔到本地node_modules/typed.js/lib/typed.min.js，记得改文件名
