### ISSUE TITLE
请教：fjGallery.min.js和fjGallery.css文件缺失

### ISSUE THREAD

**Issue by forever218** [jerryc127/butterfly-plugins#87]
![image](https://github.com/jerryc127/butterfly-plugins/assets/62095227/d4a2c666-8a6d-46ac-820d-1d8b37e577b7)
当我升级了extjs插件，并再次hexo g时，报错出现了以上错误，缺失了两个静态文件，重新安装extjs插件，问题依旧存在。以下是具体信息：
![image](https://github.com/jerryc127/butterfly-plugins/assets/62095227/beecf5c0-07e9-456e-94db-0ce60865bdee)
![image](https://github.com/jerryc127/butterfly-plugins/assets/62095227/6cb04191-3caf-4fb6-b4fe-60ced9a97d9b)
请问这是与butterfly版本过低有关吗，我该如何解决，谢谢大佬

**Comment by jerryc127** [comment]
转回旧版本的 extjs

**Comment by forever218** [comment]
> 转回旧版本的 extjs
谢谢大佬😁，extjs的版本回退至1.4.5时，问题解决了。再次感谢帮助。
